// The IP. Domain model + engines written once in commonMain, compiled to:
//   - JVM  -> consumed by :server as the verifier
//   - JS   -> consumed by :web for on-device (offline) computation
// A shared golden-vector suite (M0-07) binds both targets forever.
//
// commonMain must stay framework-free — no Spring, no JPA, no serialization
// framework. Enforced by the ArchUnit purity test in M0-06.

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

kotlin {
    jvmToolchain(libs.versions.java.get().toInt())

    jvm()

    js(IR) {
        browser()
        binaries.library()
        // M7's core-bridge consumes these declarations.
        generateTypeScriptDefinitions()
    }

    sourceSets {
        commonTest.dependencies {
            implementation(kotlin("test"))
        }

        // ArchUnit analyses JVM bytecode, so the purity rules live in the JVM test source set.
        // They still guard commonMain: commonMain compiles into the JVM target's output, which is
        // what the rules import. See ArchitecturePurityTest for why that is sufficient.
        jvmTest.dependencies {
            implementation(project.dependencies.platform(libs.junit.bom))
            implementation(libs.archunit.junit5)
        }
    }
}

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()
}

// Golden vectors are authored as plain `.vectors` data files so a domain reviewer can check them
// against an official barème, and so a new vector is a readable diff rather than escaped Kotlin.
//
// They cannot simply be loaded as test resources: `:core:jsTest` runs in a browser under Karma,
// where there is no filesystem, and KMP has no common resource-loading API. Embedding the files
// into a generated source file is what lets ONE fixture set run byte-identically on both targets —
// which is the entire point of the harness (CLAUDE.md §4.2).
val vectorsDir = layout.projectDirectory.dir("src/commonTest/vectors")
val generatedVectorsDir = layout.buildDirectory.dir("generated/goldenVectors")

val generateGoldenVectors by tasks.registering {
    description = "Embeds the .vectors data files into a commonTest source file."
    group = "build"

    inputs.dir(vectorsDir)
    outputs.dir(generatedVectorsDir)

    doLast {
        val files = vectorsDir.asFile.listFiles { f -> f.extension == "vectors" }
            ?.sortedBy { it.name }   // stable order: generated output must not depend on the filesystem
            ?: emptyList()
        require(files.isNotEmpty()) { "No .vectors files found in $vectorsDir" }

        val content = files.joinToString("\n") { it.readText() }
        val outputFile = generatedVectorsDir.get().file("GoldenVectorsResource.kt").asFile
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            buildString {
                appendLine("package fr.pacpilot.core.vectors")
                appendLine()
                appendLine("// GENERATED by :core:generateGoldenVectors — do not edit.")
                appendLine("// Source of truth: core/src/commonTest/vectors/*.vectors")
                appendLine("internal object GoldenVectorsResource {")
                appendLine("    const val CONTENT: String = \"\"\"")
                append(content)
                appendLine("\"\"\"")
                appendLine("}")
            },
        )
    }
}

kotlin.sourceSets.commonTest {
    kotlin.srcDir(generateGoldenVectors)
}
